const Providers = [{  
    "name": "Meg Wilson",
    "institution": "private practice",
    "providerType": "therapist",
    "teletherapy": "yes",
    "licenseState": "international",
    "location": "virtual",
    "queerRating": "3",
    "polyRating":"3",
    "kinkRating":"2",
    "swRating":"3",
    "commentsReCommunity": "Generally very open an accepting. Very knowledgeable about Nonmonogamy, and I like that her perspective isn't based solely on what poly looks like in city in the US.",
    "couplesTherapy": "yes",
    "website": "meg-wilson.com",
    "contact": "meg@greenant.net",
    "acceptInsurance": "no",
    "cost": "$40-50 USD/session",
    "accessibility": "Uses Doxy - all virtual, so requires internet connection",
    "comments":"Really great and affordable option. I've worked on a lot of stuff with Meg, including trauma, CTPTSD, attachment, self worth, axiety, and covid struggles. She likes mindfulness but isn't overbearing about it. I like that she will cite sources or tell me whose work she's drawing on. Great therapist; I've had a lot of insights working with her."
  }]